import { ReactComponent as editIcon } from "../assets/icons/edit-2.svg";
import { ReactComponent as deleteIcon } from "../assets/icons/delete.svg";
import { ReactComponent as slash } from "../assets/icons/slash.svg";
export const mijoz = [
  {
    id: 1,
    name: "Dina Glenn",
    phone: "(+99 893) 461-41-88",
    orderCount: 3,
    status: "Active",
    slash: slash,
    editIcon: editIcon,
    deleteIcon: deleteIcon,
  },
  {
    id: 2,
    name: "Nicolina Lindholm",
    phone: "(+99 893) 461-41-88",
    orderCount: 2,
    status: "Active",
    slash: slash,
    editIcon: editIcon,
    deleteIcon: deleteIcon,
  },
  {
    id: 3,
    name: "Ekaterina Tankova",
    phone: "(+99 893) 461-41-88",
    orderCount: 1,
    status: "Active",
    slash: slash,
    editIcon: editIcon,
    deleteIcon: deleteIcon,
  },
  {
    id: 4,
    name: "Tum Tantasatityanon",
    phone: "(+99 893) 461-41-88",
    orderCount: 1,
    status: "Active",
    slash: slash,
    editIcon: editIcon,
    deleteIcon: deleteIcon,
  },
  {
    id: 5,
    name: "Débora Barbosa",
    phone: "(+99 893) 461-41-88",
    orderCount: 1,
    status: "Active",
    slash: slash,
    editIcon: editIcon,
    deleteIcon: deleteIcon,
  },
  {
    id: 6,
    name: "Sibabalwe Rubusana",
    phone: "(+99 893) 461-41-88",
    orderCount: 6,
    status: "Active",
    slash: slash,
    editIcon: editIcon,
    deleteIcon: deleteIcon,
  },
  {
    id: 7,
    name: "Francisco Maia",
    phone: "(+99 893) 461-41-88",
    orderCount: 1,
    status: "Active",
    slash: slash,
    editIcon: editIcon,
    deleteIcon: deleteIcon,
  },
  {
    id: 8,
    name: "Wilhelm Dowall",
    phone: "(+99 893) 461-41-88",
    orderCount: 2,
    status: "Active",
    slash: slash,
    editIcon: editIcon,
    deleteIcon: deleteIcon,
  },
  {
    id: 9,
    name: "Ivan Morais",
    phone: "(+99 893) 461-41-88",
    orderCount: 8,
    status: "Active",
    slash: slash,
    editIcon: editIcon,
    deleteIcon: deleteIcon,
  },
  {
    id: 10,
    name: "Yvonne Thompson",
    phone: "(+99 893) 461-41-88",
    orderCount: 1,
    status: "Active",
    slash: slash,
    editIcon: editIcon,
    deleteIcon: deleteIcon,
  },
];
